version: '3.7'
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432